#!/bin/zsh
#
# 
# The source of binary is @ /Applications/IINA.app/Contents/MacOS/iina-cli
# but symlinked to ~/bin/
#
# From webtorrent-cli
#
# Other player cli invocations
# MPLAYER_EXEC = 'mplayer -really-quiet -noidx -loop 0'
# MPV_EXEC = 'mpv --really-quiet --loop=no'
# OMX_EXEC = `lxterminal -e omxplayer -r --timeout 60 --no-ghost-box --align center -o ${typeof argv.omx === 'string' ? argv.omx : 'hdmi'}`
~/bin/iina-cli --keep-running "$@"
