#!/bin/zsh
#

imdb=$($HOME/bin/ptgo --movie search "$@" | fzf | \
			awk -F'|' '{print $NF}' | awk -F: '{print $NF}')
[[ -z $imdb ]] && exit 0
entry=$($HOME/bin/ptgo --movie torrent $imdb | fzf)
[[ -z $entry ]] && exit 0

$HOME/bin/ptgo --movie download $(echo $entry | awk -F'|' '{print $NF}')

