#!/bin/bash
#

imdb=$($HOME/bin/ptgo --show search "$@" | fzf | \
			awk -F'|' '{print $NF}' | awk -F: '{print $NF}')
[[ -z $imdb ]] && exit 0
entry=$($HOME/bin/ptgo --show torrent $imdb | fzf)
[[ -z $entry ]] && exit 0

magnet=$(echo ${entry} | awk -F'|' '{print $NF}')
$HOME/bin/ptgo --show download "$magnet"

