#!/bin/bash

ps -ef|grep VBoxHeadless >/dev/null || \
    ( VBoxManage startvm "ubuntu" --type headless && \
    echo "Sleep 20s for ubuntu to startup ..." && sleep 20 )

echo "SSH to Ubuntu ..."
ssh -t -A -x jimxu@192.168.1.117
