#!/bin/zsh
#
VM="arch"
while ! VboxManage list runningvms |grep $VM >/dev/null; do
    echo "starting $VM vm ..."
    $HOME/bin/vboxarch
    sleep 3
done
ssh -t -A -X jimxu@arch
#/usr/bin/ssh -F /dev/null -o PubkeyAuthentication=no jimxu@192.168.1.98
