#!/bin/bash

# defines a function that deletes $2 and links to $1, unless $2 is already a link.
rm_and_link() {
  [[ ! -L "$2" ]] && rm -rf "$2" && ln -s $1 $2
}

# Links extensions
rm_and_link ~/.vscode/extensions ~/.vscode-insiders/extensions

# Links settings
rm_and_link ~/Library/Application\ Support/Code/User/settings.json ~/Library/Application\ Support/Code\ -\ Insiders/User/settings.json

# Links keybindings
rm_and_link ~/Library/Application\ Support/Code/User/keybindings.json ~/Library/Application\ Support/Code\ -\ Insiders/User/keybindings.json

exit 0
