#!/bin/bash
[[ $# = 0 ]] &&
/Applications/VMware\ Fusion.app/Contents/Library/vmrun -T ws start /Users/jimxu/Documents/Virtual\ Machines.localized/Ubuntu.vmwarevm/Ubuntu.vmx || \
/Applications/VMware\ Fusion.app/Contents/Library/vmrun -T ws start /Users/jimxu/Documents/Virtual\ Machines.localized/Ubuntu.vmwarevm/Ubuntu.vmx "$@"
