#!/bin/zsh

SPATH=$1
[[ -z $1 ]] && SPATH=$(pwd)
if [[ $SPATH =~ '/' && ! -f $SPATH ]]; then
	# it is a dir, not a file, so we just give everything from that dir.
	line=$(fd . $SPATH | fzf-tmux -d 30% -1 -0 -s -m --preview 'head -100 {}' | tr '\n' ' ')
else 
	line=$(find $SPATH | fzf-tmux -d 30% -1 -0 -s -m --preview 'head -100 {}' | tr '\n' ' ')
fi

[[ -z $line ]] && exit 0
[[ -f ${line%% } ]] && less $(echo $line) && exit 0
all=
for file in $(echo "$line"); do
	all=$all" "$SPATH/$file
done
less $(echo "$all")
exit 0
