#!/bin/bash

( VBoxManage startvm "mjro" --type headless >/dev/null ) 2>/dev/null 1>/dev/null && \
    echo "Sleep 20s for manjaro/arch to startup ..." && sleep 20

echo "SSH to Manjaro/Arch ..."
ssh -t -A -x jimxu@192.168.1.202
